CREATE SEQUENCE TARA_SEQ START WITH 1;
CREATE SEQUENCE ORAS_SEQ START WITH 1;
CREATE SEQUENCE ASOCIATIE_SEQ START WITH 1;
CREATE SEQUENCE NATIONALA_SEQ START WITH 1;
CREATE SEQUENCE CM_INTERN_SEQ START WITH 1;
CREATE SEQUENCE STADION_SEQ START WITH 1;
CREATE SEQUENCE MECI_SEQ START WITH 1;
CREATE SEQUENCE JUCATOR_SEQ START WITH 1;
CREATE SEQUENCE ANTRENOR_SEQ START WITH 1;
CREATE SEQUENCE SPONSOR_SEQ START WITH 1;

CREATE TABLE TARA (
    ID_TARA                 NUMBER DEFAULT TARA_SEQ.NEXTVAL,
    NUME                    VARCHAR2(50) NOT NULL,
    COD_ISO                 VARCHAR2(3)
        CONSTRAINT CK_COD_ISO CHECK (LENGTH(COD_ISO) = 3)
        NOT NULL,
    
    CONSTRAINT PK_TARA PRIMARY KEY (ID_TARA)
);


CREATE TABLE ORAS (
    ID_ORAS                 NUMBER DEFAULT ORAS_SEQ.NEXTVAL,
    ID_TARA                 NUMBER NOT NULL,
    NUME                    VARCHAR2(50) NOT NULL,
    
    CONSTRAINT FK_ORAS_TARA FOREIGN KEY (ID_TARA)
        REFERENCES TARA (ID_TARA),
        
    CONSTRAINT PK_ORAS PRIMARY KEY (ID_ORAS)
);

      
CREATE TABLE ASOCIATIE (
    ID_ASOCIATIE            NUMBER DEFAULT ASOCIATIE_SEQ.NEXTVAL,
    NUME                    VARCHAR2(50) NOT NULL,
    SEDIU                   NUMBER NOT NULL,
    
    CONSTRAINT FK_AS_SEDIU FOREIGN KEY (SEDIU)
        REFERENCES ORAS(ID_ORAS),
    
    CONSTRAINT PK_ASOCIATIE PRIMARY KEY (ID_ASOCIATIE)
);



CREATE TABLE CAMPIONAT_EUROPEAN (
    ID_EDITIE_EURO          NUMBER,
    TARA_GAZDA              NUMBER,
    NUME_COMPETITIE         VARCHAR2(40) NOT NULL,
    DATA_INCEPUT            DATE NOT NULL,
    DATA_SFARSIT            DATE NOT NULL,
    
    CONSTRAINT FK_CM_E_TARA FOREIGN KEY (TARA_GAZDA)
        REFERENCES TARA (ID_TARA),
    
    CONSTRAINT CK_DATE_EURO CHECK (DATA_SFARSIT > DATA_INCEPUT),
        
    CONSTRAINT PK_CME PRIMARY KEY (ID_EDITIE_EURO)
);


CREATE TABLE NATIONALA (
    ID_NATIONALA            NUMBER DEFAULT NATIONALA_SEQ.NEXTVAL,
    ID_EDITIE_EURO          NUMBER,
    ID_TARA                 NUMBER NOT NULL UNIQUE, 
    NUME                    VARCHAR2(50),
    SELECTIONER             VARCHAR2(50) NOT NULL,
    APARITII_ANTERIOARE     NUMBER NOT NULL,
    
    CONSTRAINT FK_NATIONALA_EURO FOREIGN KEY (ID_EDITIE_EURO)
        REFERENCES CAMPIONAT_EUROPEAN(ID_EDITIE_EURO),
        
    CONSTRAINT FK_NAT_TARA FOREIGN KEY (ID_TARA)
        REFERENCES TARA (ID_TARA),
        
    CONSTRAINT PK_NATIONALA PRIMARY KEY (ID_NATIONALA)
);


CREATE TABLE CAMPIONAT_INTERN (
    ID_CAMPIONAT            NUMBER DEFAULT CM_INTERN_SEQ.NEXTVAL,
    ID_ASOCIATIE            NUMBER UNIQUE,
    ID_TARA                 NUMBER UNIQUE,
    NUME                    VARCHAR2(50) NOT NULL,
    DATA_INCEPUT            DATE NOT NULL,
    DATA_SFARSIT            DATE NOT NULL,
    
    CONSTRAINT FK_CMI_ASOCIATIE FOREIGN KEY (ID_ASOCIATIE)
        REFERENCES ASOCIATIE(ID_ASOCIATIE),
    
    CONSTRAINT FK_CMI_TARA FOREIGN KEY (ID_TARA)
        REFERENCES TARA(ID_TARA),

    CONSTRAINT CK_DATE_INTERN CHECK (DATA_SFARSIT > DATA_INCEPUT),

    CONSTRAINT PK_CM_INTERN PRIMARY KEY (ID_CAMPIONAT)
);

CREATE TABLE ETAPA_CAMPIONAT (
    ID_CAMPIONAT            NUMBER,
    NUMAR_ETAPA             NUMBER,
    DATA_INCEPUT            DATE NOT NULL,
    DATA_SFARSIT            DATE NOT NULL,
    
    CONSTRAINT FK_ETAPA_CAMP FOREIGN KEY (ID_CAMPIONAT)
        REFERENCES CAMPIONAT_INTERN(ID_CAMPIONAT),
        
    CONSTRAINT CK_DATE_ETAPA CHECK (DATA_SFARSIT > DATA_INCEPUT),

    CONSTRAINT PK_ETAPA_CM PRIMARY KEY (ID_CAMPIONAT, NUMAR_ETAPA)
);


CREATE TABLE COMPETITIE_EURO_CLUB (
    ID_COMPETITIE           NUMBER,
    NUME_COMPETITIE         VARCHAR2(30) NOT NULL,
    DATA_INCEPUT            DATE NOT NULL,
    DATA_SFARSIT            DATE NOT NULL,
    NUMAR_ECHIPE            NUMBER NOT NULL,
    
    CONSTRAINT CK_DATE_CLUB CHECK (DATA_SFARSIT > DATA_INCEPUT),

    CONSTRAINT CK_NR_ECHIPE CHECK (NUMAR_ECHIPE BETWEEN 4 AND 99),

    CONSTRAINT PK_CLUB_EU PRIMARY KEY (ID_COMPETITIE)
);


CREATE TABLE FAZA_COMPETITIE (
    ID_FAZA_COMPETITIE      NUMBER,
    ID_COMPETITIE           NUMBER,
    NUME_FAZA               VARCHAR2(30) NOT NULL,
    DATA_INCEPUT            DATE NOT NULL,
    DATA_SFARSIT            DATE NOT NULL,
    
    CONSTRAINT CK_FAZA_DATE CHECK (DATA_INCEPUT < DATA_SFARSIT),
    
    CONSTRAINT FK_FAZA_EDITIE FOREIGN KEY (ID_COMPETITIE)
        REFERENCES COMPETITIE_EURO_CLUB (ID_COMPETITIE),
    
    CONSTRAINT PK_FAZA PRIMARY KEY (ID_COMPETITIE, ID_FAZA_COMPETITIE)
);
    

CREATE TABLE STADION (
    ID_STADION              NUMBER DEFAULT STADION_SEQ.NEXTVAL,
    ID_ORAS                 NUMBER NOT NULL,
    NUME                    VARCHAR2(50) NOT NULL,
    CAPACITATE              NUMBER NOT NULL,
    
    CONSTRAINT CK_STADION_CAPACITATE CHECK (CAPACITATE BETWEEN 10000 AND 300000),
    
    CONSTRAINT FK_ORAS FOREIGN KEY (ID_ORAS)
        REFERENCES ORAS (ID_ORAS),
    
    CONSTRAINT PK_STADION PRIMARY KEY (ID_STADION)
);
    

CREATE TABLE ECHIPA (
    ID_ECHIPA               VARCHAR2(3)
        CONSTRAINT CK_ID_ECHIPA CHECK (LENGTH(ID_ECHIPA) = 3),
    
    ID_CAMPIONAT            NUMBER NOT NULL,
    ID_COMPETITIE           NUMBER,
    ID_STADION              NUMBER NOT NULL,
    TIP_STADION             VARCHAR2(20) NOT NULL,
    NUME                    VARCHAR2(50) NOT NULL,
    
    CONSTRAINT FK_EC_INTERN FOREIGN KEY (ID_CAMPIONAT)
        REFERENCES CAMPIONAT_INTERN(ID_CAMPIONAT),
        
    CONSTRAINT FK_EC_EURO FOREIGN KEY (ID_COMPETITIE)
        REFERENCES COMPETITIE_EURO_CLUB(ID_COMPETITIE),
        
    CONSTRAINT FK_EC_STADION FOREIGN KEY (ID_STADION)
        REFERENCES STADION (ID_STADION),
    
    CONSTRAINT CK_TIP_STADION CHECK (TIP_STADION IN ('PROPRIU', 'INCHIRIAT')),

    CONSTRAINT PK_ECHIPA PRIMARY KEY (ID_ECHIPA)
);


-- doua chei straine catre ECHIPA, pentru a garanta ca intr-un meci joaca exact doua echipe
CREATE TABLE MECI (
    ID_MECI                 NUMBER DEFAULT MECI_SEQ.NEXTVAL,
    ID_STADION              NUMBER NOT NULL,
    DATA_MECI               DATE NOT NULL,
    
    ID_ECHIPA_GAZDA         VARCHAR2(3) NOT NULL,
    ID_ECHIPA_OASPETE       VARCHAR2(3) NOT NULL,   
    GOLURI_GAZDA            NUMBER DEFAULT 0,                   -- idee de trigger: dupa insert, actualizez coloanele in functie de echipa marcatorului
    GOLURI_OASPETE          NUMBER DEFAULT 0,
    
    CONSTRAINT FK_MECI_STADION FOREIGN KEY (ID_STADION)
        REFERENCES STADION(ID_STADION),
    
    CONSTRAINT FK_MECI_GAZDA FOREIGN KEY (ID_ECHIPA_GAZDA)
        REFERENCES ECHIPA(ID_ECHIPA),
        
    CONSTRAINT FK_MECI_OASPETE FOREIGN KEY (ID_ECHIPA_OASPETE)
        REFERENCES ECHIPA(ID_ECHIPA),
    
    CONSTRAINT CK_GOLURI CHECK (GOLURI_GAZDA >= 0 AND GOLURI_OASPETE >= 0),
    
    CONSTRAINT CK_ECHIPE_DISTINCTE CHECK (ID_ECHIPA_GAZDA <> ID_ECHIPA_OASPETE),
    
    -- pentru a garanta ca nu se pot desfasura mai multe meciuri pe acelasi stadion, in aceeasi zi
    CONSTRAINT UQ_STADION_ZI UNIQUE (ID_STADION, DATA_MECI),
    
    CONSTRAINT PK_MECI PRIMARY KEY (ID_MECI)
);

-- idee de trigger: verific daca stadionul pe care se desfasoara meciul apartine echipei gazda; daca e meci neutru -> ??


-- meciul intern este dependent de etapa campionatului in care se desfasoara
CREATE TABLE MECI_INTERN (
    ID_MECI                 NUMBER NOT NULL,
    ID_CAMPIONAT            NUMBER NOT NULL,
    NUMAR_ETAPA             NUMBER,
    
    CONSTRAINT FK_MI_MECI FOREIGN KEY (ID_MECI)
        REFERENCES MECI(ID_MECI),

    CONSTRAINT FK_MI_ETAPA FOREIGN KEY (ID_CAMPIONAT, NUMAR_ETAPA)
        REFERENCES ETAPA_CAMPIONAT (ID_CAMPIONAT, NUMAR_ETAPA),
    
    CONSTRAINT PK_MECI_INTERN PRIMARY KEY (ID_MECI)
);

-- meciul european este dependent de faza competitiei in care se desfasoara
CREATE TABLE MECI_EURO (
    ID_MECI                 NUMBER NOT NULL,
    ID_COMPETITIE           NUMBER NOT NULL,
    ID_FAZA_COMPETITIE      NUMBER,
    
    CONSTRAINT FK_ME_MECI FOREIGN KEY (ID_MECI)
        REFERENCES MECI (ID_MECI),
    
    CONSTRAINT FK_ME_FAZA FOREIGN KEY (ID_COMPETITIE, ID_FAZA_COMPETITIE)
        REFERENCES FAZA_COMPETITIE (ID_COMPETITIE, ID_FAZA_COMPETITIE),
    
    CONSTRAINT PK_MECI_EURO PRIMARY KEY (ID_MECI)
);


CREATE TABLE JUCATOR (
    ID_JUCATOR              NUMBER DEFAULT JUCATOR_SEQ.NEXTVAL,
    ID_ECHIPA               VARCHAR2(3) NOT NULL,
    ID_NATIONALA            NUMBER,
    NUME                    VARCHAR2(40) NOT NULL,              
    PRENUME                 VARCHAR2(40) NOT NULL,
    DATA_NASTERII           DATE NOT NULL,
    NATIONALITATE           VARCHAR2(20) NOT NULL,              -- nationala este null daca jucatorul nu este european; cum pot sa aflu nationalitatea?
    POZITIE                 VARCHAR2(50) NOT NULL,
    CONVOCAT                VARCHAR2(2) NOT NULL,

    CONSTRAINT FK_JUCATOR_ECHIPA FOREIGN KEY (ID_ECHIPA)
        REFERENCES ECHIPA(ID_ECHIPA),
        
    CONSTRAINT FK_JUCATOR_NATIONALA FOREIGN KEY (ID_NATIONALA)
        REFERENCES NATIONALA (ID_NATIONALA),

    CONSTRAINT CK_JUCATOR_CONVOCAT CHECK (CONVOCAT IN ('DA', 'NU')),
    
    -- jucatorul cu nationala poate fi sau nu convocat; jucatorul fara nationala (cazul non-european) nu poate fi convocat (constrangerea asigura ca nu am straini convocati)
    CONSTRAINT CK_J_NAT_CONVOCAT CHECK
        ((ID_NATIONALA IS NOT NULL AND CONVOCAT IN ('DA', 'NU'))
        OR
        (ID_NATIONALA IS NULL AND CONVOCAT = 'NU')),
    
    CONSTRAINT PK_JUCATOR PRIMARY KEY (ID_JUCATOR)
);


CREATE TABLE GOL (
    ID_MECI                 NUMBER,
    NUMAR_GOL               NUMBER,
    ID_JUCATOR              NUMBER NOT NULL,
    VALIDAT                 VARCHAR2(2)
        CONSTRAINT CK_GOL_VALID CHECK (VALIDAT IN ('DA', 'NU')),
    
    MOD_INSCRIERE           VARCHAR2(40) NOT NULL,
    AUTOGOL                 VARCHAR2(2) NOT NULL 
        CONSTRAINT CK_AUTOGOL CHECK (AUTOGOL IN ('DA', 'NU')),
        
    MINUT_GOL               NUMBER
        CONSTRAINT CK_GOL_MIN CHECK (MINUT_GOL BETWEEN 1 AND 130),
    
    CONSTRAINT FK_GOL_JUCATOR FOREIGN KEY (ID_JUCATOR)
        REFERENCES JUCATOR (ID_JUCATOR),
    
    CONSTRAINT FK_GOL_MECI FOREIGN KEY (ID_MECI)
        REFERENCES MECI(ID_MECI),
    
    CONSTRAINT PK_GOL PRIMARY KEY (ID_MECI, NUMAR_GOL)
);


CREATE TABLE ANTRENOR (
    ID_ANTRENOR             NUMBER DEFAULT ANTRENOR_SEQ.NEXTVAL,
    ID_ECHIPA               VARCHAR2(3),
    PRENUME                 VARCHAR2(30) NOT NULL,
    NUME                    VARCHAR2(30) NOT NULL,
    DATA_NASTERII           DATE,

    CONSTRAINT FK_AN_ECHIPA FOREIGN KEY (ID_ECHIPA)
        REFERENCES ECHIPA(ID_ECHIPA),
    
    CONSTRAINT PK_ANTRENOR PRIMARY KEY (ID_ANTRENOR)
);


CREATE TABLE SPONSOR (
    ID_SPONSOR              NUMBER DEFAULT SPONSOR_SEQ.NEXTVAL,
    NUME                    VARCHAR2(30) NOT NULL,
    
    CONSTRAINT PK_SPONSOR PRIMARY KEY (ID_SPONSOR)
);


CREATE TABLE SPONSORIZARE (
    ID_SPONSOR              NUMBER NOT NULL,
    ID_ECHIPA               VARCHAR2(3) NOT NULL,
    
    -- prin 'date' modelez doar anul
    DATA_INCEPUT            NUMBER(4)   
        CONSTRAINT CK_SZ_INCEPUT CHECK (DATA_INCEPUT BETWEEN 1950 AND 2030)
        NOT NULL,
        
    DATA_SFARSIT            NUMBER(4)
        CONSTRAINT CK_SZ_SFARSIT CHECK (DATA_SFARSIT BETWEEN 1950 AND 2030)
        NOT NULL,
        
    VALOARE_CONTRACT        NUMBER NOT NULL,
    
    CONSTRAINT FK_SZ_ECHIPA FOREIGN KEY (ID_ECHIPA)
        REFERENCES ECHIPA (ID_ECHIPA),
        
    CONSTRAINT FK_SZ_SPONSOR FOREIGN KEY (ID_SPONSOR)
        REFERENCES SPONSOR (ID_SPONSOR),
        
    CONSTRAINT CK_SPONSORIZARE_DATE CHECK (DATA_SFARSIT > DATA_INCEPUT),
    
    CONSTRAINT PK_SPONSORIZARE PRIMARY KEY (ID_SPONSOR, ID_ECHIPA, DATA_INCEPUT)
);


